name: Build C Programs.

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [functionpointers, bitflags, voidpointers]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt update -y
          sudo apt install gcc -y

      - name: Compile and run Programs
        run: |
          gcc -o ${{ matrix.folder }}/main ${{ matrix.folder }}/main.c 
          ./${{ matrix.folder }}/main
