name: Build C Programs.

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: sonar
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-and-run:
    needs: sonar
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [functionpointers, bitflags, voidpointers, sizeof, lookuptables]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt update -y
          sudo apt install gcc -y

      - name: Compile and run Programs
        run: |
          gcc -o ${{ matrix.folder }}/main ${{ matrix.folder }}/main.c 
          ./${{ matrix.folder }}/main

