name: Build C Programs.

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt update -y
          sudo apt install gcc -y

      - name: Compile Programs.
        run: |
          gcc -o functionpointers/main functionpointers/main.checkout
          gcc -o bitflags/main bitflags/main.c
